version: "3.1"

services:
    app:
        container_name: node-project-dev 
        build: .
        command: npm start
        ports: 
            - 3000:3000
        volumes: 
            - .:/usr/app

    mongo-express:
        container_name: mongo-express-project-dev
        image: mongo-express
        ports:
            - 5050:8081
        depends_on: 
            - mongo
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: root
            ME_CONFIG_BASICAUTH_PASSWORD: root
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
            
    mongo:
        container_name: mongo-project-dev
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        ports:
            - "27017:27017"
        volumes:
            - ./data/volume:/data/db
